/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import io.CSVReader;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.PruebaMolecular;
import structures.ListaEnlazada;
import utils.DataStore;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(null);   // Centrar ventana
        setTitle("Sistema de Pruebas Moleculares INS");
        
        // Panel por defecto
        mostrarPanel(new FormAutenticacion());
        
        //  AGREGADO: acciones de menú
        Autenticacion.addActionListener(evt -> mostrarPanel(new FormAutenticacion()));
        Estadisticas.addActionListener(evt -> mostrarPanel(new FormEstadisticas()));
    
    
    }
    
     /** Cambia el panel central dinámicamente */
   public void mostrarPanel(javax.swing.JPanel panel) {
    panel.setSize(800, 500);
    panel.setLocation(0, 0);

    getContentPane().removeAll();
    getContentPane().add(panel);
    getContentPane().revalidate();
    getContentPane().repaint();
}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Barra_Menu = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Importar = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        mantenimiento = new javax.swing.JMenu();
        Autenticacion = new javax.swing.JMenuItem();
        Busquedas = new javax.swing.JMenuItem();
        Estadisticas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Barra_Menu.setBackground(new java.awt.Color(102, 102, 255));
        Barra_Menu.setDoubleBuffered(true);

        Archivo.setText("Archivos");

        Importar.setText("Importar csv");
        Importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarActionPerformed(evt);
            }
        });
        Archivo.add(Importar);

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Salir.setText("salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        Barra_Menu.add(Archivo);

        mantenimiento.setText("Modulos");

        Autenticacion.setText("Autenticacion");
        mantenimiento.add(Autenticacion);

        Busquedas.setText("Busquedas");
        Busquedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedasActionPerformed(evt);
            }
        });
        mantenimiento.add(Busquedas);

        Estadisticas.setText("Estadisticas");
        mantenimiento.add(Estadisticas);

        Barra_Menu.add(mantenimiento);

        setJMenuBar(Barra_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void BusquedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedasActionPerformed
        // TODO add your handling code here:
         mostrarPanel(new FormBusquedas());
        
    }//GEN-LAST:event_BusquedasActionPerformed

    private void ImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Seleccionar archivo CSV");

    int resultado = chooser.showOpenDialog(this);

    if (resultado == JFileChooser.APPROVE_OPTION) {

        File archivo = chooser.getSelectedFile();

        CSVReader lector = new CSVReader();
        try {
            ListaEnlazada<PruebaMolecular> lista =
                        CSVReader.cargarCSV(archivo.getAbsolutePath());
            
            // Guardar en almacén central
                DataStore.getInstance().setPruebas(lista);

                JOptionPane.showMessageDialog(this,
                        "Archivo importado correctamente.\nTotal registros: " + lista.tamaño());

            
            
            
            // Guarda la lista en tu controlador si tienes uno            
            // controlador.setLista(lista);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al leer CSV: " + ex.getMessage());
        }
    }
    
    
    
    
    }//GEN-LAST:event_ImportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
          try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {}
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem Autenticacion;
    private javax.swing.JMenuBar Barra_Menu;
    private javax.swing.JMenuItem Busquedas;
    private javax.swing.JMenuItem Estadisticas;
    private javax.swing.JMenuItem Importar;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mantenimiento;
    // End of variables declaration//GEN-END:variables
}
